config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#index'
  # При GET запросе (HTTP) с адресом /questions, перенаправление на pages#questions
  get '/questions', to: 'pages#questions'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
# наследуемый класс позволяет работать с данными БД как с оычными классами Ruby
class Question < ApplicationRecord
  # validates создает проверки на соответствие определенным условиям
  validates :title, presence: true, length: {minimum: 3}
  validates :body, presence: true, length: {minimum: 3}

  def format_created_time
    self.created_at.strftime('%Y-%m-%d %H:%M')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    # Code here
  end
  def questions
    @questions = Question.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoR001</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav>
    <ul>
      <li><%= link_to 'Home', root_url %></li>
      <li><%= link_to 'Questions', questions_url %></li>
    </ul>
  </nav>
  <main>
    <%= yield %>
  </main>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Hello world</h1>

&copy; @niko.wolfdale   <%= Time.now %>

app/views/pages/questions.html.erb
<h1>Questions</h1>

<% @questions.each do |question| %>
  <h5><%= question.title %></h5>

  <time datatime="<%= question.format_created_time %>">
    <%= question.format_created_time %>
  </time>

  <p>
    <%= question.body %>
  </p>
<%end %>